### ISSUE TITLE
What's the advantage?

### ISSUE THREAD

**Issue by ruipacheco** [martinmoene/byte-lite#2]
What's the advantage of this over `enum class byte : std::uint8_t {};` or `using byte = uint8_t`?

**Comment by martinmoene** [comment]
`byte` in `nonstd::byte` and in `enum class byte : std::uint8_t {}` is a distinct type, whereas it is not in `using byte = uint8_t`.

*byte lite* provides bit-wise operators for `nonstd::byte` whereas `enum class byte` has none (it is not an arithmetic type).
