### ISSUE TITLE
Your byte implementation is unsafe under strict aliasing

### ISSUE THREAD

**Issue by ned14** [martinmoene/byte-lite#3]
As Richard Smith points out in https://groups.google.com/a/isocpp.org/d/msg/std-proposals/McSXSFki08I/fwKKfZqNCAAJ, your byte implementation would be unsafe under strict aliasing optimisation.

The solution is to mark up your byte type with `__attribute__((__may_alias__))` on GCC and clang, For MSVC, currently, unless you use `__declspec(noalias)` and/or `__declspec(restrict)`, everything is assumed to alias, though Microsoft promise that strict aliasing optimisation is coming at some point soon.

**Comment by martinmoene** [comment]
Thanks Niall! Addressed in 75bf4d22285564e09d46fcf6c8aeb12d620b5b5e

**Comment by martinmoene** [comment]
Todo:
- [ ] Add aliasing test
